version: '3'
services:
  weaviate:
    image: semitechnologies/weaviate:1.24.7
    ports:
      - "8080:8080"
      - "50051:50051"
    restart: always

  ml-api:
    image: ml-api
    depends_on:
      - weaviate
    ports:
      - "8000:8000"
    restart: always