name: Build and FastAPI to Docker Hub

on:
  push:
    branches: [ main ]

env:
  IMAGE: collabse-travel-gigachat-service
  DEV_TAG: dev

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Docker permission
      run: |
        sudo chmod 666 /var/run/docker.sock

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE }}:${{ github.sha }} \
        -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE }}:${{env.DEV_TAG}} .

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE }}:${{ github.sha }}
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE }}:${{env.DEV_TAG}}
